### ISSUE TITLE
[BUG] When I Boot Obsidian Sometimes Style Settings Doesn't Work.

### ISSUE THREAD

**Issue by 3axleb** [mgmeyers/obsidian-style-settings#178]
Sometimes i have no errors, sometimes this happens =/
It stops completely functioning, I have to turn off and on plugin to work again. Strangely after that error dissapears.

```
Uncaught TypeError: a.view.setSettings is not a function
    at eval (plugin:obsidian-style-settings:97:2467)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-style-settings:97:2448)
    
app.js:1 TypeError: t.view.setSettings is not a function
    at eval (plugin:obsidian-style-settings:97:1665)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-style-settings:97:1646)
    at t.<anonymous> (app.js:1:2337087)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
(anonymous) @ app.js:1
VM145 plugin:obsidian-style-settings:97

Uncaught TypeError: a.view.setSettings is not a function
    at eval (plugin:obsidian-style-settings:97:2467)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-style-settings:97:2448)
```

**Comment by iljapanic** [comment]
I've experienced the same issue today. Luckily, turning the plugin off and on fixes it for me as well.
